// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered introduction generator for portfolio websites.
 *
 * - generateIntro - Generates a professional and friendly introduction based on user-provided info.
 * - GenerateIntroInput - The input type for the generateIntro function.
 * - GenerateIntroOutput - The return type for the generateIntro function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateIntroInputSchema = z.object({
  name: z.string().describe('Your name'),
  skills: z.string().describe('A comma-separated list of your key skills'),
  experience: z.string().describe('A brief description of your experience'),
  goals: z.string().describe('Your career goals'),
});
export type GenerateIntroInput = z.infer<typeof GenerateIntroInputSchema>;

const GenerateIntroOutputSchema = z.object({
  introduction: z.string().describe('A professional and friendly introduction.'),
});
export type GenerateIntroOutput = z.infer<typeof GenerateIntroOutputSchema>;

export async function generateIntro(input: GenerateIntroInput): Promise<GenerateIntroOutput> {
  return generateIntroFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateIntroPrompt',
  input: {schema: GenerateIntroInputSchema},
  output: {schema: GenerateIntroOutputSchema},
  prompt: `You are a professional copywriter specializing in crafting introductions for personal portfolio websites.

  Based on the information provided, generate a short, engaging, and professional introduction for the hero section of a portfolio website.

  Name: {{{name}}}
  Skills: {{{skills}}}
  Experience: {{{experience}}}
  Goals: {{{goals}}}

  Introduction:`, 
});

const generateIntroFlow = ai.defineFlow(
  {
    name: 'generateIntroFlow',
    inputSchema: GenerateIntroInputSchema,
    outputSchema: GenerateIntroOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
